apiVersion: v1
kind: Service
metadata:
  name: express-srv
  labels:
    app: express
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30036
  selector:
    app: express
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deploy
  labels:
    app: express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express_api
        image: 894213385675.dkr.ecr.eu-west-1.amazonaws.com/devops-12:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80